config/routes.rb
RedditClone::Application.routes.draw do

  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :votes 
  end  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :votes
  belongs_to :user

  def vote_count
    votes.recent.up.count - votes.recent.down.count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  enum direction: [:up, :down]
  scope :recent, -> { where(created_at: 1.week.ago..Time.now) }

  after_create :send_email

  def send_email
    VoteMailer.notification(self, post).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end


  def create  
    @post = Post.new(params[:post].permit(:title, :comment))
    @post.user = current_user
    if @post.save 
      redirect_to ('/posts')
    else
      render 'new'
    end
  end  

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @votes = @post.votes.new direction: params[:direction]
    @votes.user = current_user
    if @votes.save
      WebsocketRails[:votes].trigger 'new', {id: @post.id , new_vote_count: @post.vote_count }
      render json: {vote_count: @post.vote_count}
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/posts">RedditClone</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Add Post', new_post_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in?%>
            <li><div class="log-in-message">Logged in as <%= current_user.email %></div></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

  </nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <p class="yield"><%= yield %></p>
</div>

</body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <div class="post">
      <div class="col-md-12">
        <h3><%= post.title %></h3>
        <p class="comment"><%= post.comment %></p>
        <p class="votes-text" data-id="<%= post.id %>"><%= pluralize post.vote_count, 'vote' %></p>
        <div class="vote-buttons">
          <div class="col-md-1">
            <%=button_to 'Upvote', post_votes_path(post, direction: :up), class: "btn btn-success"%>
          </div>
          <div class="col-md-1">
            <%=button_to 'Downvote', post_votes_path(post, direction: :down), class: "btn btn-danger"%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  No posts yet
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>